### ISSUE TITLE
did:pkh support

### ISSUE THREAD

**Issue by kimdhamilton** [circlefin/verite#378]
did:pkh meets the guidelines for did method selection we've outlined. Would be great to add support:
https://github.com/w3c-ccg/did-pkh/blob/main/did-pkh-method-draft.md

**Comment by bumblefudge** [comment]
Anyone implementing or assessing verite with did:pkh use-cases or architectures in mind can reach out to me on discord, i'm <GH username>#1488 there.

**Comment by kimdhamilton** [comment]
Consider using did-kit libs

**Comment by DuaneDamian** [comment]
All good mate.

**Comment by kimdhamilton** [comment]
Use this: https://www.spruceid.dev/didkit/didkit-packages/javascript
